// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9mwurfp4cBubFAn_ah45xDXSxmnAVLl0',
    appId: '1:320735591270:web:be7440d775536c567aa6a7',
    messagingSenderId: '320735591270',
    projectId: 'netflix-clone-test-7c2b1',
    authDomain: 'netflix-clone-test-7c2b1.firebaseapp.com',
    storageBucket: 'netflix-clone-test-7c2b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlp_BGn7dP51WMngnYuEKWuKvqVxjMcCw',
    appId: '1:320735591270:android:684c859c0cc589dc7aa6a7',
    messagingSenderId: '320735591270',
    projectId: 'netflix-clone-test-7c2b1',
    storageBucket: 'netflix-clone-test-7c2b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzXLzViMzxX_Lwr_ZuP4kj4tiaNdW1pS4',
    appId: '1:320735591270:ios:162c0a4ed13c81d97aa6a7',
    messagingSenderId: '320735591270',
    projectId: 'netflix-clone-test-7c2b1',
    storageBucket: 'netflix-clone-test-7c2b1.appspot.com',
    iosBundleId: 'com.example.flutterNetflix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzXLzViMzxX_Lwr_ZuP4kj4tiaNdW1pS4',
    appId: '1:320735591270:ios:84f85d4516e29d1e7aa6a7',
    messagingSenderId: '320735591270',
    projectId: 'netflix-clone-test-7c2b1',
    storageBucket: 'netflix-clone-test-7c2b1.appspot.com',
    iosBundleId: 'com.example.flutterNetflix.RunnerTests',
  );
}
